#pragma once


#define TITLE "Clace"
#define BG_COLOR CLITERAL(Color){ 43, 43, 43, 255 }
#define CELL_COLOR_1 CLITERAL(Color){ 235, 236, 208, 255 }
#define CELL_COLOR_2 CLITERAL(Color){ 115, 149, 82, 255 }
#define WINDOW_W 1400
#define WINDOW_H 900
#define BOARD_W 800
#define BOARD_H 800
#define CELL_SIZE (BOARD_W / 8)
#define PIECE_SIZE 110
#define BOARD_ALPHA 1.0f
#define PIECE_SCALE 0.6f
#define PIECE_ALPHA 1.0f
#define PADDING 50.0f
#define BOARD_START_X PADDING
#define BOARD_START_Y PADDING
#define BOARD_END_X (BOARD_START_X + BOARD_W)
#define BOARD_END_Y (BOARD_START_Y + BOARD_H)
#define INFO_START_X (BOARD_END_X + PADDING)
#define INFO_START_Y PADDING
#define INFO_END_X (WINDOW_W - PADDING)
#define INFO_END_Y (WINDOW_H - PADDING)
#define INFO_FONT_SIZE 20
#define PANEL_START_X INFO_START_X
#define PANEL_START_Y (INFO_START_Y + BOARD_H / 2)
#define PANEL_W (WINDOW_W - PADDING - BOARD_W - PADDING - PADDING)
#define PANEL_H (WINDOW_H - PADDING - BOARD_H / 2 - PADDING)
#define FEN_PANEL_W 900
#define FEN_PANEL_H 60
#define FEN_PANEL_X ((WINDOW_W - FEN_PANEL_W) / 2)
#define FEN_PANEL_Y ((WINDOW_H - FEN_PANEL_H) / 2)
#define BUTTON_W 95
#define BUTTON_H 30
#define BUTTON_FONT_SIZE 28