#pragma once

//#define BOARD_USE_PRE_CALCULATED

#define BOARD_STANDARD_RAY_ATTACKS
//#define BOARD_BRANCHLESS_RAY_ATTACKS
//#define BOARD_ONTHEFLY_RAY_ATTACKS

//#define PROFILER
//#define PERFT_USE_CACHE

#define PERFORMANCE_TESTS